cmd/add.go, cmd/exec.go, cmd/login.go, cmd/root.go, lib/config.go, lib/okta.go, lib/provider.go, lib/sessions.go, vendor/vendor.json
Move from importing 99designs/aws-vault/keyring to using 99designs/keyring directly.  Most of the changes are adapting to the new keyring API.
Also updates vendor to use a fork of keybase/go-keychain that allows for building on all versions of go.  We can go back to the original if https://github.com/keybase/go-keychain/pull/22 gets merged
=> Fix keyring

lib/sessions.go
There's also a few other references to vault.  Not sure which others are obsolete.
```
09:47:13 $ ag 'vault'
cmd/add.go
35:             LibSecretCollectionName: "awsvault",
cmd/exec.go
118:            LibSecretCollectionName: "awsvault",
cmd/login.go
66:             LibSecretCollectionName: "awsvault",
133:            "https://signin.aws.amazon.com/federation?Action=login&Issuer=aws-vault&Destination=%s&SigninToken=%s",
README.md
29:Exec will assume the role specified by the given aws config profile and execute a command with the proper environment variables set.  This command is a drop-in replacement for `aws-vault exec` and accepts all of the same command line flags:
70:We use 99design's keyring package that they use in `aws-vault`.  Because of this, you can choose between different …
```
=> fix session label

cmd/add.go, cmd/exec.go, cmd/login.go, vendor/vendor.json
- Use fork of keyring that allows setting ACL's correctly
- Use login keychain
=> Less auth prompts

cmd/exec.go
I'm building a utility invoked by `aws-okta`. It would be useful for the utility to know what profile its running under.
Current behavior:
```
$ aws-okta exec prod -- env | grep prod
```
New behavior:
```
$ aws-okta exec prod -- env | grep prod
AWS_PROFILE=prod
```
=> set AWS_PROFILE to arg

lib/okta.go, lib/struct.go
This supports okta's token MFA type, for Google Authenticator and other software based OTP solutions, as well as token:hardware for YubiKeys.
Note: this does not support U2F (https://developer.okta.com/docs/api/resources/authn#verify-u2f-factor)
=> Support for token MFA type

cmd/exec.go
- Some apps (for example, packer) use the AWS_PROFILE setting to
determine which profile to load out of ~/.aws/config shared config.
The problem is that these profiles don't have associated
credentials, so those applications fail.  Instead, don't set
profile, and the applications just use the AWS_ACCESS_KEY_ID and
AWS_SECRET_ACCESS_KEY vars.
=> setting AWS_PROFILE as part of exec leads to errors in some apps:

cmd/login.go
Workaround for #17 
This is just like [aws-vault](https://github.com/99designs/aws-vault/blob/master/cli/login.go#L187) and allows other browsers to be called via shell configuration like this:
```shell
cat `which awslogin`
#!/bin/bash
aws-okta login $1 --stdout | xargs -t /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --incognito --new-window
```
This is borrowed from: https://github.com/FernandoMiguel/kb/blob/master/Chrome/aws-vault.md
=> allow login url to go to stdout

README.md, lib/provider.go
Get the aws_saml_url from profiles -- with fallback to "okta" section.
The `aws_saml_url` can now be set in the "okta" ini section, or on a per profile basis. This is useful if, for example, your organization has several Okta Apps (i.e. one for dev/qa and one for prod, or one for internal use and one for integrations with third party providers).
=> Allow for multiple Okta Apps

lib/prompt.go
Tried compiling tool for windows and encountered these issues before getting it to work.
First I need to fix keyring dependency: [PR](https://github.com/99designs/keyring/pull/19)
After I am able to compile this line failed with "The handle is not defined" in windows. Used syscal.Stdin as suggested on this [thread](https://github.com/golang/go/issues/11914):
I tested changes on Windows and Mac.
=> fix password prompt error in windows

cmd/add.go, cmd/exec.go, cmd/login.go, lib/keyring.go
Not ideal, because it requires supplying the keyring password
for every operation, but useful in situations where access to
more powerful keyrings are not available.
Addresses #37.
=> Support file keyring backend

lib/provider.go, lib/sessions.go
We've noticed a behavior of `aws-okta` that doesn't work with some of our IAM policies that rely on a person's username coming through each time they `AssumeRole` into one of our accounts. Also, it makes identifying people who use `aws-okta` in CloudTrail more difficult: their username shows up as a timestamp most of the time.
You can see this issue by running `aws sts get-caller-identity` twice in succession:
```
? thopkins -> ~ $ aws-okta exec my-account -- aws sts get-caller-identity
INFO[0001] Requesting MFA
Enter MFA Code: 000000
{
"Account": "ACCOUNT_ID",
"UserId": "SOMEID:thopkins",
"Arn": "arn:aws:sts::ACCOUNT_ID:assumed-role/role/thopkins"
}
? thopkins -> ~ $ aws-okta exec my-account -- aws sts get-caller-identity
{
"Account": "ACCOUNT_ID",
"UserId": "SOMEID:1522780778660795625", …
```
=> store session name in keychain to use it during assumeRoleFromSession

lib/duo.go, lib/utils.go
In some integrations, it appears that hitting /frame/web/v1/auth with an
empty POST will not result in a 302, as expected, but returns a 200,
with a response body that contains a form with hidden input fields, sid
and certs_url. In order to continue with authentication, this form data
must be POSTed to the same /frame/web/v1/auth, which then triggers the
already handled 302 redirect flow.
This commit adds a branch to DoAuth where on StatusOK, we parse out the
values of the sid and certs_url inputs. These values are then passed
recursively to DoAuth again, so that another pass through the function
may submit these values and handle the expected 302 redirect flow. This
was found to be the order of operations needed from chrome dev tools
inspection of the iframe API calls, and it is working …
=> Allows for form based Duo Authentication Fixes #26

README.md
The README regarding config appears to have drifted from the code, as
one must use 'source_profile' to indicate which role one uses as a hub
to assume another. This commit updates the README example with the
proper config key.
Also, 'role_arn' is added to the integrations-auth example profile, as
it is required.
=> Update readme to match config parsing code

cmd/login.go
Changed vault -> Okta. Minor thing but confused me slightly when I got this page after timeout in AWS;
"Amazon Web Services Sign In
Your session has expired.To start a new session, click the link provided by your administrator:aws-vault To logout, click here"
=> Fix issuer name

cmd/exec.go
Useful for when you have tooling that wants to know which role you're running in.
We don't want to use AWS_PROFILE, since that's significant to some tools.
Instead, add an AWS_OKTA_PROFILE env var, which is the name of the profile being used.
=> Add an AWS_OKTA_PROFILE env attribute

.circleci/config.yml, .gitignore, Makefile, Makefile.release, Makefile.tools, nfpm.yaml.tmpl
Basically copied https://github.com/segmentio/chamber/pull/129
Fixes https://github.com/segmentio/aws-okta/issues/79
=> Add deb/rpm package building and publishing

lib/duo.go
if result_url is empty use existing cookie (if not empty)
=> fix for duo empty result_url

README.md
You solved a problem you didn't even know about. :) I had `aws-okta` working for `aws-cli`, but whenever I tried to access my EKS cluster with `kubectl`, it would fail since `aws-iam-authenticator` doesn't know anything about `aws-okta`.
This works so long as `aws-okta` uses ENV variables to authenticate with AWS.
Adding this info to README should increase SEO friendliness on the topic and help others like myself find it in the future as EKS gains traction.
=> Add README update to show support for EKS and Kubectl.

lib/okta.go
I'm having this output when `keyring.Get` fails:
```
DEBU[0000] couldnt get okta creds from keyring: %sunexpected end of JSON input
```
Cause `%s` is not being interpolated.
=> Use log.Debugf instead of log.Debug

lib/keyring.go, lib/prompt.go
This allows redirecting the output of exec without the prompt getting in the way.
=> Use stderr for passphrase prompt

README.md
If you have used other okta aws cli tools such as https://github.com/oktadeveloper/okta-aws-cli-assume-role - you might assume that you need to append .okta.com" to your organization name.
```
$ aws-okta add
Okta organization: mycompany.okta.com
Okta username: elliotmoore
Okta password:
INFO[0014] Added credentials for user elliotmoore
```
Results in: 
```
$ aws-okta login blah
Failed to authenticate with okta.  Please check that your credentials have been set correctly with `aws-okta add`
```
making clear that organization name should not be appended with .okta.com
as its already added here: https://github.com/segmentio/aws-okta/blob/master/lib/okta.go#L72
```
Okta organization: mycompany
```
Perhaps a better PR would warn the user during `aws-okta add` or ignore if exists.
For now this …
=> Document: Don't append .okta.com to org name

README.md, cmd/exec.go, cmd/login.go
As AWS allows for configuration of maximum session duration per-role it seems appropriate and useful to be able to set this per-profile in the AWS config.
Also adds documentation for the environment variables `AWS_SESSION_TTL` and `AWS_ASSUME_ROLE_TTL`.
=> Add support for assume_role_ttl in config profiles

.circleci/config.yml, cmd/add.go, cmd/exec.go, cmd/login.go, cmd/root.go, lib/duo.go, lib/okta.go, lib/provider.go, vendor/vendor.json
This breaks a few abstractions -- and hence warrants some explanation
The Duo MFA flow in aws-okta is predicated on something like this
1. user pings okta
2. if duo, call duo API /frame/prompt which sends a push
3. this is where we have problem.. with yubikey vs push
-- instead of async waiting, yubikey can write directly to stdin and
continue, because the initial factor call wants the passcode to be
passed in
4. Then in Status call turns out the first status call returns empty
for Push but second can wait. It's opposite for Yubikey
The next step is on how to give the users a choice. I thought of few
options and settled on a flag, where the user flow is - X method
didn't work, I'll try another one. But because of the providers
nesting and calling OktaClient, it MFADevice field had to be …
=> Support Yubikey configured in Duo for 2FA

lib/okta.go
> aws-okta add
hangs due to mis-matched MFA type.
=> use oktaFactorType instead of oktaFactorId for MFA type

cmd/add.go, cmd/root.go, go.mod, go.sum, lib/config.go, lib/duo.go, lib/okta.go, lib/provider.go, lib/sessions.go, vendor/vendor.json
This may not be the expected usage of aws-okta, but I am using the lib component of aws-okta for another tool. The problem I am facing is that the existing tool imports sirupsen as lowercase, and therefore seems to be unable to vendor aws-okta properly.
I am not a Go expert, so I don't know if this is the right approach, but this seems to fix my problem. The guideline in [sirupsen's README](https://github.com/sirupsen/logrus) suggests that "Everything using logrus will need to use the lower-case: github.com/sirupsen/logrus".
=> Rename Sirupsen to sirupsen

lib/okta.go
This is a pretty small change, but the issue always hamstrings me when I fly and I usually forget about it right after I land.
Currently either the TLS handshake (10s default) or subsequent connection can time out on a slow network - for example, airplane wi-fi. This makes those timeouts 60s apiece so those attempts have a better chance of getting through successfully.
=> Increase timeouts to allow auth over slow connections

cmd/exec.go, cmd/list.go
I can never remember the names of the profiles I have configured, so this command will list them for you.
Caveat: It assumes you only care about profiles that are assuming from another role; it only lists profiles that have a source_profile.
=> add a `list` command

README.md, cmd/add.go, cmd/exec.go, cmd/login.go, cmd/root.go, lib/okta.go, lib/provider.go
Supercedes #97/#73, and streamlines changes for this PR and #85.
=> Implement config option for which MFA to use

lib/okta.go
Adds the default behavior of pulling proxy information from environment variables.
=> Add Proxy support for OktaClient.Get

Dockerfile
Even in a build stage it can only hurt to keep the build cache around in its own layer
=> remove apt cache layer

cmd/add.go, lib/okta.go
- Added CLI arguments for Okta organization (deprecated?), Okta region, Okta domain and Okta username. Reason: We would rather give our employees a single simple command to run already configured with our company's variables, rather than tell them "when you see this prompt, type this"
- Updated oktaDomain example value to `["+organization+".okta.com]` because after reading the code it seems like this is actually the format that is derived, not `"+region+".okta.com`.
- Included a log line for the oktaDomain to verify this
- Indentation fixes
=> Added CLI arguments for aws-okta add

lib/duo.go
Ran into #121 while trying to get setup with Duo + U2F. After comparing the flow in the code to the browser it looks like aws-okta isn't calling the Duo status endpoint properly. That is required to exchange the txid we get for something Okta will take.
I've tested this code with both U2F and Tokens and both now work.
=> fix: ensure that DoStatus is called for u2f devices

lib/okta.go
Updated from #66 c/o @Incisive
=> MFA input validation

cmd/root.go
Bug is illustrated here:
```
LDmbp: ~ $ aws-okta add --domain segment.okta.com --username leif@segment.com -d
Okta password: 
DEBU[0005] domain: segment.okta.com                     
DEBU[0005] Step: 1                                      
DEBU[0005] Failed to validate credentials: Failed to authenticate with okta: &errors.errorString{s:"POST https://segment.okta.com/api/v1/authn: 401 Unauthorized"} 
Failed to validate credentials
LDmbp: ~ $ bash okta.sh 
Which team are you on?
Options are: app, biztech, foundation, personas, platform, product, success
Enter the team based on the table in the setup doc:
foundation
Pulling down /Users/leifdreizler/.aws/config
✔️: Your old aws config has been backed up in /tmp/awsconfig-358d044b5eb575f6b9e5623a20ab5535
✔️: Your aws config was successfully …
```
=> Avoid clobbering the  --username flag when running add subcommand

Makefile.release, vendor/vendor.json
So we can rebuild in the face of temporary failure. 
For example, this publish failed https://circleci.com/gh/segmentio/aws-okta/452, then this attempt to rerun failed https://circleci.com/gh/segmentio/aws-okta/454
Using this branch and a prerelease tag:
- [initial run](https://circleci.com/workflow-run/84c493b1-e4f8-4128-989e-a714e00fb5b7)
- [rebuild](https://circleci.com/workflow-run/78ecb644-9c7e-4aac-9a84-2123d0b1fb1b)
=> fix: idempotent publishes

cmd/login.go
We were troubleshooting some issues with `aws-okta login ...` and discovered that the error, in this case, was being swallowed. This happens if you try to run `aws-okta login ...` before doing `aws-okta add`.
=> Don't swallow errors from login operations

cmd/env.go, cmd/shell.go
This PR adds a new command, `aws-okta shell` which prints to stdout sourceable commands that set environment variables to the relevant aws profile.
The output looks like this:
```bash
./aws-okta shell test
```
```bash
export AWS_ACCESS_KEY_ID=FOO
export AWS_SECRET_ACCESS_KEY=BAR
export AWS_OKTA_PROFILE=test
export AWS_DEFAULT_REGION=us-east-1
export AWS_REGION=us-east-1
export AWS_SESSION_TOKEN=[LONG TOKEN]
export AWS_SECURITY_TOKEN=[LONG TOKEN]
```
and I use it like this:
```bash
source <(aws-okta shell test)
```
The inspiration for this was to provide an in-tool command to easily switch between AWS profiles, so that a user can use the aws-cli without have to run it through the `aws-okta exec` command.  I'm switching accounts multiple times a day, and it's useful to just have the …
=> feat: Add `env` command that prints a sourceable configuration to STDOUT.

lib/provider.go
It seems to me that as of today the max Okta session timeout is 90 days.
Could you please help double check this is the fact, and review the PR accordingly, thanks!
=> feat: increase MaxSessionDuration to 90 days

lib/okta.go
I previously suggested this in #127, just providing a PR for it.
=> Hint to use add when password has changed

cmd/env.go
source <$(aws-okta env profile) will get you 'no such file or directory: export',
or similar. We just need to execute the command in a subshell.
=> fix: Typo in documentation of 'env'

lib/okta.go
Our users would get constant "unexpected EOF" errors when trying to authenticate with 2FA against okta.
We traced the cause to trying to decode the transport encoding (gzip) on the chunked body stream in the response.  
This causes `ReadAll` to return an `io.EOF` err even when it should not: https://github.com/segmentio/aws-okta/blob/b1140c3a208d3181325baf9bffe29cbc75ad58d5/lib/okta.go#L516
The fix that has worked is to add a header to prevent okta from encoding the response.
=> Disabled transport encoding to okta to prevent EOF

cmd/login.go
Heyo,
Super minor change - I'm currently in the process of migrating from `aws-vault` to `aws-okta` and a frequent use case I have is
```shell
$ aws-vault login -s profile | pbcopy
```
and then opening the link in a new private browser session.
I noticed that `aws-okta` doesn't provide a shorthand option for the flag and requires typing out `-stdout` each time; this PR enables usage of the shorthand `-s` flag.
=> Enable Shorthand Flag for Stdout on the Login Command

go.mod, go.sum, vendor/modules.txt
https://github.com/99designs/keyring/issues/49
=> Upstream added a go-mod-compatible tag v1.0.0

cmd/exec.go, lib/provider.go
Storing current AWS assumed-role as `AWS_ROLE`. This allows the user to
easily check the assumed role when running aws-okta.
=> feat: adding current role as env var

lib/okta.go, lib/provider.go
Currently this project assumes we would always want to use us-gov-west-1 as it is statically set https://github.com/segmentio/aws-okta/blob/master/lib/okta.go#L217. This PR adds support so it is region agnostic.
=> feat: support for aws govcloud profiles

lib/mfa/fido.go, lib/okta.go, lib/struct.go
adds support for U2F FIDO devices such as yubikey. The U2F device must
already be registered with Okta and be plugged in and available for use.
retry if open fails, there are issues with the low level `hid_open` call
that we rely on in `hidapi`.
These are the libraries we depend on:
https://github.com/marshallbrekka/go-u2fhost/blob/master/hid/wrapper.go
https://github.com/marshallbrekka/go.hid
https://github.com/signal11/hidapi
=> feat: enable FIDO U2F MFA

cmd/env.go, cmd/exec.go, lib/provider.go
The call to `p.GetRoleArn()` added in https://github.com/segmentio/aws-okta/commit/396d453 was forcing a separate auth event. That broke session caching in 0.23.0 and 0.23.1.
So the first run of `aws-okta` would auth twice, including a second 2FA prompt. Every subsequent call to `aws-okta` then also required 2FA confirmation.
This PR modifies GetRoleARN to take the creds as an argument.  Those creds are fetched immediately before anyways.
This also adds the `AWS_OKTA_ASSUMED_ROLE_ARN` and `AWS_OKTA_ASSUMED_ROLE` environment variables to the `env` subcommand so that it is consistent with `exec`.
This replaces a couple other PRs:
Closes: #216
Closes: #217
=> fix: don't force reauth when calling GetRoleARN

cmd/exec.go, lib/provider.go
This lets the user specify a role ARN that will override what is present
in their profile. If no value is present in the profile it will be
added.
Co-authored-by: Aaditya Sondhi <aaditya@autonomic.ai>
=> feat: allow override of role arn to assume

lib/okta.go, lib/provider.go, lib/saml/struct.go, lib/utils.go
If the `role_arn` is provided, attempt to assume that role. No change to
current behaviour.
If `role_arn` is empty or not present in the profile and there is more than one
role then display the full list of roles the user can assume and prompt
them to choose the role to assume. The choice will be sticky for the
rest of the session for that profile. Whne the session ends they will be
prompted again to choose a role.
=> enable prompt if role not provided

README.md, cmd/add.go, lib/okta.go, lib/provider.go
Add ability for user to specify keyring key to separate provider data (including MFA and domain) per aws profile. Similar to #91 request.
Setup accounts:
```ini
aws-okta add --keyringKey=okta-creds-account-a
aws-okta add --keyringKey=okta-creds-account-b
```
Define keyring key for each profile:
```ini
[profile account-a]
aws_saml_url = home/amazon_aws/woezQTbGWUaLSrYDvINU/214
role_arn = arn:aws:iam::<account-id>:role/<okta-role-name>
okta_keyring_key = okta-creds-account-a
[profile account-b]
aws_saml_url = home/amazon_aws/adbcQTbGaDAA4rYDvINU/123
role_arn = arn:aws:iam::<account-id>:role/<okta-role-name>
okta_keyring_key = okta-creds-account-b
```
=> feat: Support for multiple Okta accounts (add keyring key configuration per profile)

cmd/env.go, cmd/exec.go, lib/provider.go
GovCloud support was added in #197 / b4e7839 and #204 / 9787f11.
Taking the role as an env var was added in #208 / 396d453, which added
`GetRoleARN` which ignored region and, thus, broke GovCloud.
Both of these were released as v0.23.0, so no version of aws-okta
supported GovCloud.
Separately, `GetRoleARN` was split into a `lib` function and a `Provider`
function in #218 / e13ae0f, which left behind a code duplication TODO
and an unused Provider function.
=> fix: make GetRoleARN support GovCloud

README.md
I looked for auto-completion for `aws-okta` on google and only found this issue: https://github.com/segmentio/aws-okta/issues/116. I didn't see any documentation in the wiki or README about it, so I thought I'd add a short section in the README.
=> docs: Adds shell completion section to README

cmd/cred-process.go
Hello there,
I was reading #143 and because I'm in the same situation where I need to use `credential_process`, I made a quick PR.
Here's the new command help:
```
$ aws-okta help cred-process
cred-process generates a credential_process ready output
Usage:
aws-okta cred-process <profile> [flags]
Examples:
[profile foo]
credential_process = aws-okta cred-process profile
Flags:
-a, --assume-role-ttl duration   Expiration time for assumed role (default 1h0m0s)
-h, --help                       help for cred-process
-p, --pretty                     Pretty print display
-t, --session-ttl duration       Expiration time for okta role session (default 1h0m0s)
Global Flags:
-b, --backend string              Secret backend to use [keychain pass file]
-d, --debug                       Enable debug …
```
=> Add credential_process support

cmd/env.go, cmd/exec.go, lib/provider.go
This implements #190 as the `AWS_OKTA_SESSION_EXPIRATION` environment variable which is the expiration date as the number of seconds from the Unix epoch.
=> feat: Export expiration as AWS_OKTA_SESSION_EXPIRATION

lib/provider.go, lib/utils.go
- Break it down by account ID to make it easier to find roles to select.
Roles will be displayed similar to list below
```
Account: 111111111111
0 - arn:aws:iam::111111111111:role/my-role-1
1 - arn:aws:iam::111111111111:role/my-role-2
2 - arn:aws:iam::111111111111:role/my-role-3
Account: 222222222222
3 - arn:aws:iam::222222222222:role/other-role-1
4 - arn:aws:iam::222222222222:role/other-role-2
Select Role to Assume:
```
- Fix error when provided profile does not have a role_arn
- User will be prompted to choose role from list of roles.
=> feat: sort roles listed in roles prompt

Makefile.release
https://wiki.ubuntu.com/Releases says:
- eoan 2019-10-17 -- 2020-07
- cosmic 2018-10-18 -- 2019-07-18
Should address #233 when released. Not sure if this will require a PATCH release, or we can hack around it.
=> pipeline: add ubuntu 19.10 (eoan ermine); rm ubuntu cosmic

internal/sessioncache/key_profilearn.go, lib/provider.go
The profileARN can be overriden as part of the exec call.
This fixes a bug with the following commands:
- aws-okta exec profile --assume-role-arn role1 -- command
- aws-okta exec profile --assume-role-arn role2 -- command
The second command would be run using role1 since the session cache
thinks there's already a valid session. The cache lookup logic does not
take the assume role override into account when looking for a session.
=> fix: Include the profileARN for the session cache key

lib/okta.go
After digging around a bit, I realised that you do not provide the `Endpoint` parameter to the `aws.Config{}` struct for sts. Because newer regions requires v2 tokens (see: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_enable-regions.html and here: https://docs.aws.amazon.com/cli/latest/reference/iam/set-security-token-service-preferences.html) enabled on the global endpoint (and this is not enabled per default), using regional endpoints is safer as they're guaranteed to work with the region you're trying to access.
This fixes #225
=> Use regional endpoints for STS #225

lib/prompt.go, lib/utils.go
This enables scriptability of aws-okta, this appears to already be the case for some of the prompting things.
(it hangs forever at the end of the output, I found it is prompting for the Role here)
```console
$ ./aws-okta exec "$ROLE" -- echo hi > log
INFO[0001] Requesting MFA. Please complete two-factor authentication with your second device 
INFO[0001] Select a MFA from the following list         
INFO[0001] 0: DUO (web)                                 
INFO[0001] 1: GOOGLE (token:software:totp)              
0
INFO[0004] Sending Push Notification...                 
INFO[0005] Device: phone1           
```
(output is doctored a bit to obfuscate our account ids / etc.)
```console
$ ./aws-okta exec "$ROLE" -- echo hi > log
INFO[0001] Requesting MFA. Please complete two-factor …
```
=> fix: Produce prompts on stderr

README.md, cmd/cred-process.go, cmd/env.go, cmd/exec.go, cmd/login.go, cmd/write-to-credentials.go
If "session_ttl" exists in config profile, use it as if --session-ttl was provided on the CLI.
This creates config parity between "session-ttl" and "assume-role-ttl".
I believe only one term is necessary, but we can address that in a later issue.
=> feat: Support "session_ttl" config param in every command (#251)

lib/okta.go
Based on @Chippiewill PR #213
When using MFA, Okta expects the device token cookie `DT` in addition to
the session ID cookie `sid`. If MFA is required in the Okta app and this
cookie is not sent the session fails. This causes `aws-okta` to go
through the entire authentication flow again, eliminating any benefits
of session caching.
This change persists the device token the same way as the session ID.
I've kept the existing API identical, adding new function calls that
take an OktaCookies struct.
Manual testing with Push notification and Okta AWS application setup to require MFA "Per Session" and "Once per Day".
With both patches in place, the Okta session is successfully reused, without MFA prompt, to create new AWS STS tokens when the previous STS token is expired.
=> feat: Persist device token cookie in keystore to prevent repeated MFA prompt

lib/duo.go
Printing a "touch the u2f device" prompt to stdout interferes with the AWS credential_process API, which expects pure JSON on stdout:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html
Before output:
```
% aws iam list-users --profile abcdefg
Expecting value: line 1 column 1 (char 0)
```
After output:
```
% aws iam list-users --profile abcdefg
{
"Users": [
{
"Path": "
```
=> Don't print the "touch the device" prompt to stdout

lib/okta.go
GetSAMLLoginURL was using hard-coded "okta-creds" instead of the lookup
for OktaAccountName, in cases where multiple accounts are used, this can
result in building an incorrect login URL
=> Update missing conversion of OktaAccountName

cmd/write-to-credentials.go
This should keep old crud from being included at the end of the file if it shrinks.
=> Set O_TRUNC when re-writing credentials file

lib/duo.go, lib/okta.go
A new session ID is being returned from the last frame status call before issuing another redirect to get the last signature. This session ID is needed for the redirect to work. We were passing a session ID but it was stale.
Best guess as to root cause is that something must have changed in the /frame/status endpoint to return this new session ID. All I know is that this restores functionality.
=> Fix session ID handling

lib/duo.go
Looks like Duo switched their secret APIs back on us. This should support them both.
Refinement on https://github.com/segmentio/aws-okta/pull/293
=> fix: add dual duo sid API support

cmd/cred-process.go
The Expiration field conveyed the wrong value. It's changed to be the
same value that's used in aws-okta exec.
=> Fix cred process expiration

lib/provider.go
Follow up to #307.
STS clients are created in multiple places with the lack of STS regional endpoint configuration. The required option was added to all of them. Also, I've tested the entire workflow with `aws-okta exec` command call + enabled HTTP request to debug logging and now everything looks good:
```
...
DEBU[0006] Step 4: Assume Role with SAML
DEBU[0006] Using region: us-east-1
2020/12/28 15:58:59 DEBUG: Request sts/AssumeRoleWithSAML Details:
---[ REQUEST POST-SIGN ]-----------------------------
POST / HTTP/1.1
Host: sts.us-east-1.amazonaws.com
...
DEBU[0007] Using session 3QFD, expires in 59m58.959948s
2020/12/28 15:59:01 DEBUG: Request sts/GetCallerIdentity Details:
---[ REQUEST POST-SIGN ]-----------------------------
POST / HTTP/1.1
Host: sts.us-east-1.amazonaws.com
...
```
=> Add STS Regional Endpoint Support To Other STS Clients
